from __future__ import annotations

# Canonical Megabike configuration (do not parse/exec *.txt at runtime)

RACES: list[str] = [
    "omloop-het-nieuwsblad",
    "faun-ardeche-classic",
    "la-drome-classic",
    "kuurne-brussel-kuurne",
    "trofeo-laigueglia",
    "strade-bianche",
    "nokere-koerse",
    "milano-torino",
    "gp-de-denain",
    "bredene-koksijde-classic",
    "milano-sanremo",
    "classic-brugge-de-panne",
    "e3-harelbeke",
    "gent-wevelgem",
    "dwars-door-vlaanderen",
    "gran-premio-miguel-indurain",
    "ronde-van-vlaanderen",
    "scheldeprijs",
    "brabantse-pijl",
    "paris-roubaix",
    "amstel-gold-race",
    "la-fleche-wallone",
    "liege-bastogne-liege",
]

# Race tier per race (0/1/2)
RACES_RANK: dict[str, int] = {
    "omloop-het-nieuwsblad": 1,
    "faun-ardeche-classic": 2,
    "la-drome-classic": 2,
    "kuurne-brussel-kuurne": 2,
    "trofeo-laigueglia": 2,
    "strade-bianche": 1,
    "nokere-koerse": 2,
    "milano-torino": 2,
    "gp-de-denain": 2,
    "bredene-koksijde-classic": 2,
    "milano-sanremo": 0,
    "classic-brugge-de-panne": 1,
    "e3-harelbeke": 1,
    "gent-wevelgem": 1,
    "dwars-door-vlaanderen": 1,
    "gran-premio-miguel-indurain": 2,
    "ronde-van-vlaanderen": 0,
    "scheldeprijs": 2,
    "brabantse-pijl": 2,
    "paris-roubaix": 0,
    "amstel-gold-race": 1,
    "la-fleche-wallone": 1,
    "liege-bastogne-liege": 0,
}

# Points table per tier; index = rank-1
RANK_POINTS: dict[int, list[int]] = {
    0: [
        240,
        150,
        120,
        100,
        85,
        75,
        65,
        55,
        50,
        45,
        40,
        35,
        30,
        28,
        26,
        24,
        22,
        20,
        18,
        16,
        14,
        13,
        12,
        11,
        10,
        9,
        8,
        7,
        6,
        5,
        5,
    ],
    1: [
        200,
        125,
        100,
        80,
        70,
        60,
        50,
        45,
        40,
        35,
        30,
        25,
        20,
        18,
        16,
        14,
        12,
        10,
        9,
        8,
        7,
        6,
        5,
        4,
        3,
        3,
        3,
        3,
        3,
        3,
        3,
    ],
    2: [
        150,
        85,
        70,
        55,
        45,
        40,
        35,
        30,
        25,
        20,
        16,
        14,
        12,
        10,
        9,
        8,
        7,
        6,
        5,
        4,
        3,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
    ],
}


